### ISSUE TITLE
Suggestion for calling flags from other packs

### ISSUE THREAD

**Issue by Bjorn0411** [Alexofp/BDCC#101]
Currently, its quite easy to set up a simple block that checks if a character exists from another datapack, and then, for example, switches out characters in scenes, or adds entire new scenes. You could create a questline for a character from a completely different pack, allowing a really cool level of collaboration.

However, whilst we can call characters no problem, we cant call other datapack flags. Meaning if we wanted to add additional scenes, or alternate paths, to quests, or add additional scenes to a character after they've had their quests completed, this is currently not possible. It's only possible to create fresh start stuff.

It'd be really cool if we could check for flags from other datapacks, even change them. It would open up a huge opportunity for collaborative packs.

A suggestion for implementation.
Add a "get exists [datapack/mod]" codeblock to let you check if a thing exists, outputs as a boolean. this means you could add to any datapack or mod, without them having characters to check for.
Then also, instead of the dropdown when selecting the flags in your datapack, it opens a menu with 3 tabs at the top, first is the flags in your datapack, 2nd is the flags in the base game, 3rd is all flags from other datapacks
Or, keep the dropdown but a "more..." button at the bottom of the dropdown that opens this menu.
As long as you only add calls for flags that might not exist, inside an if then block that checks if the datapack/mod exists, it shouldnt throw any errors.

**Comment by CanInBad** [comment]
I think flags are stored by $"{ModuleName}.{FlagName}", this is true for modules but I don't know if it is the case for datapacks

**Comment by Bjorn0411** [comment]
> I think flags are stored by $"{ModuleName}.{FlagName}", this is true for modules but I don't know if it is the case for datapacks

Having fiddled around by putting a raw string block inside the flag selection box, and then typing in the "$"{ModuleName}.{FlagName}"" (obviously with my pack and flag in there instead) and any variations I could think of, I cant find a way to use that command to grab a flag from another pack.
If you were able to make it work, I'd love to know.

**Comment by Alexofp** [comment]
You can use the raw string to get any flag, yeah.
Module flags are ModuleID.FlagID   (with a dot in the middle)
Datapack flags are DatapackID:FlagID    (with a : in the middle)

It's just that you can't check if the flag exist x3. It will always error out if that flag doesn't exist

**Comment by Alexofp** [comment]
btw, if you add other datapack as a requirement it will be loaded too when testing scenes, no need for special saves

**Comment by Bjorn0411** [comment]
> You can use the raw string to get any flag, yeah. Module flags are ModuleID.FlagID (with a dot in the middle) Datapack flags are DatapackID:FlagID (with a : in the middle)

So, I'm trying to do that right now, but it doesnt seem to work?
Below are pictures
into the raw string I tried "brevmanscharacterpack2:metkatherine" and "brevmanscharacterpack2:MetKatherine" (difference is one is capitalized like the flag) both without the quotes
I am using a save I know has the pack enabled.

<img width="1912" alt="image" src="https://github.com/user-attachments/assets/5bedf0bb-d8c5-4bdf-9fe1-f5546c084261">

<img width="1909" alt="image" src="https://github.com/user-attachments/assets/6cdd3e95-6880-4144-a98e-1980fae996a9">

<img width="1919" alt="image" src="https://github.com/user-attachments/assets/ff55cbc4-5d4e-4604-85c7-bb1cd2af7e99">

**Comment by Alexofp** [comment]
Oh yeah, I see it now. Yeah, sorry, I limited to only the current datapack flags. Sorry x3

**Comment by Bjorn0411** [comment]
No worries! I do have _plans_ to use it, but not in the near future, I have _plenty_ of other ideas to work on first haha.

**Comment by dogboi1120** [comment]
can i get a new invite
![image_2024-08-03_122632768](https://github.com/user-attachments/assets/f368c936-9bc6-4139-bc51-bcd7c308823c)

**Comment by Alexofp** [comment]
Probably fixed by now
