### ISSUE TITLE
Wiki Contribution: How to setup development environment

### ISSUE THREAD

**Issue by CanInBad** [Alexofp/BDCC#113]
with additional fixes to previously added pages

[diff](https://github.com/CanInBad/BDCC_wiki/compare/69d69c34620e40dd7acc3683e714466755c77961...3684c6056d4894357c587724dac3e9c376faabae)

pull *rebase* the [modified](https://github.com/CanInBad/BDCC_wiki/tree/modified) branch

**Comment by Alexofp** [comment]
Thankies, I think I did it. I think there are a few little problems x3

**Comment by CanInBad** [comment]
you can list what they are and ill fix it

**Comment by Alexofp** [comment]
![pic](https://github.com/user-attachments/assets/e9f9355a-6576-4d94-88a7-9e38981a4cfd)
```
> [!IMPORTANT] Do not get the mono version
> .NET or mono version is a separate binaray that support C#, **BDCC isn't built on mono**
```
should probably be
```
> [!IMPORTANT]
> Do not get the mono version. Mono or .NET version is a separate binary that support C#, **BDCC isn't built on mono**
```

**Comment by Alexofp** [comment]
I don't have time/desire to proof-read the whole thing, very sorry, meow. But that was the most obvious thing

**Comment by CanInBad** [comment]
fixed

**Comment by Alexofp** [comment]
Thankies ^^

**Comment by CanInBad** [comment]
I just notice now that the page still refer to home page about the reason why we can't migrate to godot 4

its very late for me so could you please uncomment the old information 🙏

**Comment by Alexofp** [comment]
did it
