### ISSUE TITLE
ModularDialogue Registers too early

### ISSUE THREAD

**Issue by Mindstormsman** [Alexofp/BDCC#116]
The new Modular Dialogue system was clearly designed with the intent to allow modders to add their own form banks however because it is an autoload and registers in on ready it has already registered the forms before mods are loaded

The register functions should be delayed until after mod loading

**Comment by CanInBad** [comment]
I believe you can just do

```gd
var listFormsToRegister = ["res://path/to/dialogueform1.gd", "res://path/to/dialogueform2.gd"]

for i in listFormsToRegister:
    var form = i.new()
    ModularDialogue.registerForm(form)
```

**Comment by Mindstormsman** [comment]
Closer to
```GDScript
var formBanks = ["res://path/to/formBank1.gd", "res://path/to/formBank2.gd"]

for i in formBanks:
	var bank = load(i).new()
	ModularDialouge.registerFormBank(form)
```
individual forms have extra data associated with them
and this is just for the forms, this code would have to be copied again for fillers and adders

If this is a bug, I'm worried that if we use the work around and the bug is fixed mods will throw an error per line of text they add as forms are attempting to be registered twice

I don't suppose there is a way to close an issue as `Don't fix` as opposed to `Won't fix`

**Comment by CanInBad** [comment]
make a pr to add such in module lol, Module class already does this sort of boilerplate

https://github.com/Alexofp/BDCC/blob/main/Modules/Module.gd#L44-L136

as for the concern, I guess we have to wait for @Alexofp for confirmation if they're going to fix it as you intented it to be or left this one a "feature"

**Comment by Alexofp** [comment]
Yeah I moved it now so it will now register the lines during the GlobalRegistry loading (after mods). Should be good enough
