### ISSUE TITLE
Won't start after enabling mod manager

### ISSUE THREAD

**Issue by Yeetzy128** [Alexofp/BDCC#117]
I play on Andriod, Idk whats wrong or what's causing the long loading. The phone notifies me that it stops responding

**Comment by CanInBad** [comment]
Please wait for it to build BDCC.pck, wait up to 10 minutes.

**Comment by pl23** [comment]
Optionally deleting the file would also fix that issue because it will build a new one but like he said it could take up to 10 or 20ish minutes

**Comment by pl23** [comment]
Hey I get it if it ain't broke why fix it but it does lead us into some technical debt and limitations for no reason

**Comment by pl23** [comment]
This issue has been fixed maybe this can be closed?
