### ISSUE TITLE
Pawns couldn't spawn properly

### ISSUE THREAD

**Issue by CockMongler1964** [Alexofp/BDCC#118]
im playing on the android version, 0.1.6, with some mods and datapacks and then i decide to start a new game. as i create my character and leave my cell, i notice that there's very small amount of pawns, less than 10 or even 5, while in settings i choosed 120 pawns. 
reinstalling doesn't help, i just get back my few old saves where everything's fine, but when creating new save problem with pawns happens again. what do i do?

**Comment by Alexofp** [comment]
First 5 days will have reduced pawn amount (5 and 10 like you have noticed), to not overwhelm the player, its intended ^^. Just sleep 5 times
