### ISSUE TITLE
Scene of NovaWonScene on The UnderGround floor has not chastity check 

### ISSUE THREAD

**Issue by DoberBit** [Alexofp/BDCC#126]
After defeating the guard named Nova in the arena at the `NovaWonScene`.`power_suit` for `offer_cock` stage access there is no check for the player's chastity and it looks funny like a husky sucking an imaginary rod
![image](https://github.com/user-attachments/assets/0eeb3491-28c8-4572-b135-6bee0f318973)

**Comment by Alexofp** [comment]
There is no check because the scene is written to support chastity. The animation just doesn't fit x3. I changed it

Thank you
