### ISSUE TITLE
modding help

### ISSUE THREAD

**Issue by TheDogOfChaos** [Alexofp/BDCC#20]
I'd like to learn how make a mod for a new set of (albeit very expensive) pills that, upon consumption, instantly causes the recieving party to have every possible orifice immediately filled with an absurd amount of a specific fluid type, dependant on the pill consumed.

Furthermore, I'd like to learn how to make it so that the player can buy a (vastly cheaper) set those pills, but they're empty and have to have the desired fluid transferred to the pill first.

Following on from that, I'd like to learn how to turn into filled pill items (same items as the pre-filled ones i mentioned earlier) depending on their content, but have it so that if you fill it with your or someone else's cum, it keeps note of the DNA and fills the recipient with the cum of that specific character. (also if you buy a pre-filled cum pill it just sets the DNA to one of these: "an anonymous inmate", "an anonymous guard", "an anonymous nurse", or just "anonymous").

**Comment by dogboi1120** [comment]
can you help me make a mod pls
![Screenshot 2024-05-21 173935](https://github.com/Alexofp/BDCC/assets/115887934/69eb1085-b80f-427a-8db3-6eaf761ed34d)
i made her sorry if she has mods

**Comment by pl23** [comment]
This should be marked as completed there's a separate GitHub repo for modding
