### ISSUE TITLE
Console command, when missing arguments command_entry's paramCount index does not exist

### ISSUE THREAD

**Issue by CanInBad** [Alexofp/BDCC#78]
When using a console command that requires argument, it crashes due to trying to call non existing index of `"paramCount"`
https://github.com/Alexofp/BDCC/blob/main/UI/DebugUI/ConsoleSingleton.gd#L77

**Comment by Alexofp** [comment]
I made the console before I made the handy debug panel, console became kinda useless after that, heh

**Comment by CanInBad** [comment]
![Fine, I'll do it myself](https://c.tenor.com/u8YEMwIfJGMAAAAC/tenor.gif)
