### ISSUE TITLE
Wiki contribution

### ISSUE THREAD

**Issue by CanInBad** [Alexofp/BDCC#81]
I have finished a page detailing how to add a new floor as well as other minor edits
Please review and merge (preferably rebase)
https://github.com/CanInBad/BDCC_wiki/tree/modified1

[diff](https://github.com/CanInBad/BDCC_wiki/compare/main...modified1)

**Comment by Alexofp** [comment]
Looks nice

Can you help me with how to merge it? x3

I did git clone https://github.com/Alexofp/BDCC.wiki.git
what would I do next x3

**Comment by Alexofp** [comment]
I did it but looks like it doesn't like that you added .md at the end

**Comment by CanInBad** [comment]
do you want me to fix or would you like to fix it?

**Comment by Alexofp** [comment]
Thank you <333
