### ISSUE TITLE
Wiki Contribution: How to get mods revamp

### ISSUE THREAD

**Issue by CanInBad** [Alexofp/BDCC#82]
There is still no link to it in Home page but the page itself is a lot better <sub>in my opinion</sub>

Though there are other changes you can check diff [here](https://github.com/CanInBad/BDCC_wiki/compare/6522e275a2df5202680cbe06a92a8001a17f1189...e86b35ea4686faf5e22536cbcfad0a0a06eec39f)

the branch itself to merge: https://github.com/CanInBad/BDCC_wiki/tree/modified2

**Comment by Alexofp** [comment]
Thank you, looks nice <3

**Comment by CanInBad** [comment]
wiki merged, closing
