### ISSUE TITLE
proposal: species ideas/bodytypes

### ISSUE THREAD

**Issue by dogboi1120** [Alexofp/BDCC#84]
corgis
any taurs
any dog breed
wiener dogs
new bodytypes
buff
femenine
short
tall
etc

**Comment by dogboi1120** [comment]
@Alexofp pls acklowledge me

**Comment by CanInBad** [comment]
Either learn to fork and make a pull request or move on. I don't think they would make a new animation system for taurs.

We've discussed this topic (not with the repo owner) on discord and so far we only got those answers

**Comment by dogboi1120** [comment]
oh ok but are other types ok

**Comment by dogboi1120** [comment]
i can't code i need help

**Comment by dogboi1120** [comment]
![Screenshot 2024-05-16 183354](https://github.com/Alexofp/BDCC/assets/115887934/a1a990cb-71fa-47ec-993b-9849b124163b)
this is the futrthest i got with my species before i gave up

**Comment by dogboi1120** [comment]
hello i tried to make a species blurrans

**Comment by CanInBad** [comment]
Hello, please do not spam others inbox and start learning. All the resources are here to get you started https://github.com/Alexofp/BDCC/wiki

If you don't succeed, try try again.

If you have any questions regarding modding please visit our discord `modding-help` channel.

@Alexofp please close this as not planned

**Comment by Alexofp** [comment]
Yeah, this is not the place to ask for new species, sorry
