### ISSUE TITLE
Wiki Contribution: User support pages

### ISSUE THREAD

**Issue by CanInBad** [Alexofp/BDCC#85]
I understand that the wiki is meant for making mods but since you already had "How To Install Mods" page, might as well right?

Here's the diff [link](https://github.com/CanInBad/BDCC_wiki/compare/e86b35ea4686faf5e22536cbcfad0a0a06eec39f...607e331551867df2373f87be6a9820503c05f9b7)

Branch to merge https://github.com/CanInBad/BDCC_wiki/tree/modified3

**Comment by Alexofp** [comment]
Yeah, not a bad idea, thank you lots <3
