### ISSUE TITLE
DEV branch Datapack characters all start with 0 fluid volume and (mostly) doesnt generate any.

### ISSUE THREAD

**Issue by Bjorn0411** [Alexofp/BDCC#96]
This is a somewhat minor issue
 - [ ] When loading Datapack characters, their cum volume is 0, and it stays at 0 untill you find them as an encounter, where their cum amount begins to simulate and increase

I placed down some "(character1) cums inside (character2) (hole) using (member) scale (#)" blocks in a scene with multiple characters, and noticed their breeder's streak perks triggered, so they came succesfully, but the recipient didnt get cummed inside of at all unless the giver was the pc.
I thought at first there was some issue with the block not triggering that status effect on the receiver if an NPC is the giver. But as I was writing out a report here about that being an issue, I checked how much cum was supposed to be dropped and noticed my datapack characters have 0 current volume, their max volume is still fine to be clear.

If you meet the character in the encounters menu, or randomly, they will start from 0 but begin to build up a cum volume.
and, sleeping in your bed does reset their volumes to 100%. Both times the volume persisted into the scenes, so they dont loose it when the scene starts, its just that when they are first loaded in, they have 0.
BUT sleeping seems to only refill their volumes IF they have been met in the past.

For example, I've got 4 characters in this scene im working on (more technically but those are the ones that matter)
I encounter C1 in a random encounter, defeat him, leave him be, then sleep.
Then I trigger the scene im working on, and C1 has a full volume of cum, but C2 has 0 breast volume. And later when C3 & C4 show up, they have 0 cum volume.
I reload from start, encounter C3, then sleep, and do the scene again, now C1 and C3 have cum volume but the rest are entirely empty.
Except at one point C1 stopped getting more? I think once I load the save, it stops simulating his cum volume increasing, but does remember how much he had, but maybe not based on save data? But I really dont know

Here's the steps I took:

I meet C1, defeat him, start sex and undress him just to make sure his volume is building. Then end sex. I then sleep, encounter the scene, see C1 has 100% volume, and he cums succesfully into C2. Due to breeder perks he still has x% left in his tank.
The scene continues and C1 meets C3 and C4, both have 0% volume and C1 has x%.
I reload the save from when I slept earlier, meet C3, fight and defeat him, sleep, watch the scene again and C1 has x% now, where last time he had 100%, he cums in C2 again, then C3 shows up and has 100% in the tank like he should.
I figure maybe the cum data isnt stored in the save, but is drawn from memory, and so will persist through saves.
I turn the game off, which would clear the memory, but loading the save up again C1 still has x%

I dont know coding, but my recommendation would be more or less:
"IF: character cum amount is not actively tracked and simulated, THEN: upon loading character, set volume to 100%" (but written in human terms because again, idk coding :P)

If you'd like I can send you the exact datapack im building, (and tell you exactly what steps to take in the scenes to reproduce what I've been doing.) So you can test things for yourself.

And im sorry if my explanations are a little messy ^^

**Comment by Alexofp** [comment]
You write a lot x3. The orgasm block drains balls, make sure its -after- any cum inside/onto blocks. Otherwise, I will investigate

**Comment by Bjorn0411** [comment]
Sorry for how long it is yeah XD I massively over explain in a pretty autistic way. ("ohh god, what if they missunderstand the tiniest detail!")
Yes how I originally tested it was:
place 2 x cum on y blocks, one is npc cumming in npc, the other is pc cumming in npc
in the scene afterwards, the cum from the pc is added into its hole(I put em on different holes) but not the one from the npc.

You can see the issue by loading a datapack character, add them to a scene, encounter scene and then hover over their penis in the animation window, there itll say they have 0/x volume.

**Comment by Alexofp** [comment]
Yeah, thankies, I will fix it soon

**Comment by Bjorn0411** [comment]
No rush for me! Doesnt hurt my ability to work on scenes. And I will try my best to be a bit more succinct in any future error reports, gonna try to remember the obvious fact that if you need more info you can just ask for it lol

**Comment by Alexofp** [comment]
I made them start with full balls, should fix the issue I hope. Only newly-loaded chars will have that. And the 'milk' code blocks now also has refill versions too
