### ISSUE TITLE
DEV Branch "Stretch orifice of x size y" giving error

### ISSUE THREAD

**Issue by Bjorn0411** [Alexofp/BDCC#97]
- [ ] Error when using the "Stretch (orifice)" codeblock.

Set orifice to vagina, character be an npc, size any number.
when run, says:
[CrotchScript Error at line 4, block: LewdDoStretchHole] Stretch amount must be a number, got vagina instead
guessing you accidentally flipped what values its taking from
"painfully stretch" doesnt return an error, but im not sure how or if it works, as adding it doesnt seem to change the {pc.pussyStretch} command

**Comment by Bjorn0411** [comment]
Also, I figure most of the time stretching happens in the game, it is based on dick size, but there isnt a "get dick size" block to set the "[...] size()" to be based on.
How is stretching normally handled in the game?

**Comment by Alexofp** [comment]
painfull stretching only works on player, it adds status effects for painfully stretched anus/vag, it doesn't stretch anything, heh
The other thing I will fix, thanks

**Comment by Alexofp** [comment]
Should be fixed
